server:
  forward-headers-strategy: framework
  port: 9000

application:
  name: @project.artifactId@

build:
  version: @project.version@

applications:
  api:
    names: service1,service2,service3,service4